version: "3.9"
services:
  db:
    image: mariadb:10
    container_name: adviseme-db
    volumes:
      - ./DB/AdviseMeDB.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: adviseme
      MARIADB_USER: adviseme_app
      MARIADB_PASSWORD: app_pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=pass"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: capstone_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/code
      - ./pdf_scraper:/pdf_scraper:ro
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mysql+pymysql://root:pass@adviseme-db/adviseme
      - PDF_SCRAPER_PATH=/pdf_scraper/scrape_pdfs.py
      - API_WORKDIR=/code
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: capstone_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/code
      - ./front-end/node-modules:/code/node-modules
    environment:
      - VITE_API_URL=http://api:8000/api
    depends_on:
      - api
