/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvisorDashboard: typeof import('./src/components/AdvisorDashboard.vue')['default']
    APIButton: typeof import('./src/components/APIButton.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DashboardTabs: typeof import('./src/components/DashboardTabs.vue')['default']
    DropForm: typeof import('./src/components/DropForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentDashboard: typeof import('./src/components/StudentDashboard.vue')['default']
  }
}
